---
system_config:
  definitions:
    - os_flavors: ['mac']
      check_install: |
        test $(defaults read com.apple.finder AppleShowAllFiles) = '1'
      install: |
        # show hidden files in Finder
        # not needed anymore b/c of cmd + shift + . shortcut?
        defaults write com.apple.finder AppleShowAllFiles -boolean true; killall Finder # to restart

        computer_name=${USER}-mac
        sudo /usr/sbin/scutil --set ComputerName "${computer_name}"
        sudo /usr/sbin/scutil --set LocalHostName "${computer_name}"
        sudo /usr/sbin/scutil --set HostName "${computer_name}"
        dscacheutil -flushcache

    - os_flavors: ['debian']
      check_install: |
        test 1 = 1
      install: |
        # echo 'manual setup..., do what you like'
